eureka:
  client:
    register-with-eureka: false
server:
  port: 8085
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: student
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/students/**
        - id: school
          uri: http://localhost:8075
          predicates:
            - Path=/api/v1/schools/**